

---


# ADALL ASSIGNMENT


---

> This notebook is for ADALL ASSIGNMENT


---

## Introduction and Content

This dataset contains 7,000 synthetic transaction records designed to bridge the gap between "clean" classroom data and the messy reality of production environments. It provides a mix of 12 numerical and categorical features that simulate typical banking and e-commerce signals, like transaction velocity, customer age, and geographic distance from home

## 📖 Data Dictionary

| Column | Description |
|--------|-------------|
| `person_age` | Age of the person |
| `person_gender` | Gender of the person	Categorical|
| `person_education` | Highest education level |
| `person_income` | Annual income |
| `person_emp_exp` | Years of employment experience |
| `person_home_ownership` | Home ownership status (e.g., rent, own, mortgage) |
| `loan_amnt` | Loan amount requested |
| `loan_intent` | Purpose of the loan |
| `loan_int_rate` | Loan interest rate |
| `loan_percent_income` | Loan amount as a percentage of annual income |
| `cb_person_cred_hist_length` | Length of credit history in years |
| `credit_score` | Credit score of the person |
| `previous_loan_defaults_on_file` | Indicator of previous loan defaults |
| `loan_status (target variable)` | Loan approval status: 1 = approved; 0 = rejected |

---

URL = https://www.kaggle.com/datasets/taweilo/loan-approval-classification-data/data

EDA: https://www.kaggle.com/code/fatemehmohammadinia/personal-loan-acceptance-prediction-95-accuracy

This project focuses on building a classification model to predict the acceptance of personal loans by bank customers based on various demographic and financial features such as Age, Experience, Income, Family, Credit Card Average Spending (CCAvg), Education, Mortgage, and other account-related attributes including Securities Account, CD Account, Online Banking, and Credit Card Ownership.

---

Through this analysis, we aim to:

Explore and understand the structure, quality, and relationships within the dataset.
Perform data cleaning, feature transformation, and scaling to prepare the data for machine learning models.
Visualize key patterns, distributions, and correlations between features and loan acceptance behavior.
Build and evaluate classification models such as Logistic Regression, Naive Bayes, and K-Nearest Neighbors (KNN).
Interpret model outcomes to identify key factors influencing the likelihood of a customer accepting a personal loan.
This model is designed to assist banks and financial institutions in improving marketing strategies, customer targeting, and loan offer optimization by predicting which clients are most likely to accept a personal loan.

## What Is This Project About?
Personal loan acceptance depends on several demographic and financial factors such as income, education, family size, mortgage, credit card spending (CCAvg), and existing account relationships.
Accurate prediction of which customers are likely to accept a personal loan helps banks and financial institutions optimize their marketing campaigns and target the right customers more effectively.

---

In this project, we explore how machine learning classification models can be used to predict whether a customer will accept a personal loan based on their financial and demographic attributes.
The dataset is based on real-world customer banking data that includes behavioral and financial indicators.

##Why Predict Loan Acceptance?

Predicting loan acceptance is useful for:

Banks & financial institutions: Targeting customers with higher acceptance probability

Marketing teams: Designing cost-efficient and personalized loan offers

Risk analysts: Understanding which customers are less likely to respond

Decision-makers: Enhancing strategic planning for future campaigns
By applying classification models, we can transform customer data into actionable insights that improve business outcomes.

##Prompt example

You are helping a data analytics student prepare a laptop pricing dataset for modelling.

- Do not assume external knowledge.
- Do not say to drop a column just because it is listed as a warning.
- Keep the answer concise.
- Do not invent causes.
- Do not overclaim.

In [2]:
# Libraries used in this notebook
import os
import shutil
import platform
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import joblib

# Modelling libraries used later in Session 2
from sklearn.model_selection import train_test_split, ShuffleSplit, cross_val_score
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import ShuffleSplit, cross_val_score
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

from xgboost import XGBRegressor

RANDOM_STATE = 42

# Make wide tables easier to read in Colab
pd.set_option('display.max_columns', 100)

print('Setup complete')

Setup complete

In [3]:
github_raw_url = 'https://raw.githubusercontent.com/jiannyuhs-hue/ADALL_github/refs/heads/main/ADALL%20assignment/loan_data.csv'

df = pd.read_csv(github_raw_url)

print('Dataset loaded successfully.')
print('Shape:', df.shape)
display(df.head())

# This cell loads the laptop price dataset directly from GitHub.
# The GitHub raw URL points to the actual CSV file, not the normal GitHub preview page.
# pd.read_csv() reads the CSV file and stores it as a pandas DataFrame called df.
# df.shape shows the number of rows and columns in the dataset.
# df.head() displays the first 5 rows so we can quickly check that the data loaded correctly.

Dataset loaded successfully.
Shape: (45000, 14)

,person_age,person_gender,person_education,person_income,person_emp_exp,person_home_ownership,loan_amnt,loan_intent,loan_int_rate,loan_percent_income,cb_person_cred_hist_length,credit_score,previous_loan_defaults_on_file,loan_status
0,22.0,female,Master,71948.0,0,RENT,35000.0,PERSONAL,16.02,0.49,3.0,561,No,1
1,21.0,female,High School,12282.0,0,OWN,1000.0,EDUCATION,11.14,0.08,2.0,504,Yes,0
2,25.0,female,High School,12438.0,3,MORTGAGE,5500.0,MEDICAL,12.87,0.44,3.0,635,No,1
3,23.0,female,Bachelor,79753.0,0,RENT,35000.0,MEDICAL,15.23,0.44,2.0,675,No,1
4,24.0,male,Master,66135.0,1,RENT,35000.0,MEDICAL,14.27,0.53,4.0,586,No,1

In [4]:
# Default method: copy the prompt into the chatbot manually.
RUN_API_CELLS = True
OPENAI_MODEL = 'gpt-5.4-nano'
client = None

# Only use this section if your tutor has asked you to call the API from Colab.
# You must first save OPENAI_API_KEY in Colab Secrets.

if RUN_API_CELLS == True:
    from google.colab import userdata
    from openai import OpenAI

    api_key = userdata.get('OPENAI_API_KEY')
    client = OpenAI(api_key=api_key)
    print('OpenAI client is ready.')
else:
    print('Manual chatbot mode. Copy the prompts when they appear.')

# This cell prepares the notebook to use the OpenAI API, if needed.
# RUN_API_CELLS controls whether the notebook uses the API or manual chatbot mode.
# If RUN_API_CELLS is True, the notebook will try to connect to OpenAI using an API key.
# If RUN_API_CELLS is False, students can copy the prompt and paste it into ChatGPT manually.
# OPENAI_MODEL stores the model name that will be used later when sending prompts.
# client starts as None first, then becomes an OpenAI client after the API key is loaded.
# userdata.get('OPENAI_API_KEY') reads the API key saved in Colab Secrets.
# OpenAI(api_key=api_key) creates the connection object used to call the API.

OpenAI client is ready.

In [5]:
# Convert the first few rows to a string to send to OpenAI
# data_preview = df.head(10).to_string()  another way

data_preview = df.head(100).to_csv(index=False)

print(data_preview)

person_age,person_gender,person_education,person_income,person_emp_exp,person_home_ownership,loan_amnt,loan_intent,loan_int_rate,loan_percent_income,cb_person_cred_hist_length,credit_score,previous_loan_defaults_on_file,loan_status
22.0,female,Master,71948.0,0,RENT,35000.0,PERSONAL,16.02,0.49,3.0,561,No,1
21.0,female,High School,12282.0,0,OWN,1000.0,EDUCATION,11.14,0.08,2.0,504,Yes,0
25.0,female,High School,12438.0,3,MORTGAGE,5500.0,MEDICAL,12.87,0.44,3.0,635,No,1
23.0,female,Bachelor,79753.0,0,RENT,35000.0,MEDICAL,15.23,0.44,2.0,675,No,1
24.0,male,Master,66135.0,1,RENT,35000.0,MEDICAL,14.27,0.53,4.0,586,No,1
21.0,female,High School,12951.0,0,OWN,2500.0,VENTURE,7.14,0.19,2.0,532,No,1
26.0,female,Bachelor,93471.0,1,RENT,35000.0,EDUCATION,12.42,0.37,3.0,701,No,1
24.0,female,High School,95550.0,5,RENT,35000.0,MEDICAL,11.11,0.37,4.0,585,No,1
24.0,female,Associate,100684.0,3,RENT,35000.0,PERSONAL,8.9,0.35,2.0,544,No,1
21.0,female,High School,12739.0,0,OWN,1600.0,VENTURE,14.74,0.13,3.0,640,No,1
22.0,female,High School,102985.0,0,RENT,35000.0,VENTURE,10.37,0.34,4.0,621,No,1
21.0,female,Associate,13113.0,0,OWN,4500.0,HOMEIMPROVEMENT,8.63,0.34,2.0,651,No,1
23.0,male,Bachelor,114860.0,3,RENT,35000.0,VENTURE,7.9,0.3,2.0,573,No,1
26.0,male,Master,130713.0,0,RENT,35000.0,EDUCATION,18.39,0.27,4.0,708,No,1
23.0,female,Associate,138998.0,0,RENT,35000.0,EDUCATION,7.9,0.25,4.0,583,No,0
23.0,female,Master,600891.0,5,MORTGAGE,30000.0,DEBTCONSOLIDATION,10.65,0.05,3.0,670,Yes,0
23.0,male,Bachelor,144943.0,0,RENT,35000.0,EDUCATION,7.9,0.24,4.0,663,No,0
23.0,female,High School,111369.0,0,RENT,35000.0,MEDICAL,20.0,0.31,4.0,694,No,1
23.0,male,Bachelor,136628.0,0,RENT,35000.0,DEBTCONSOLIDATION,18.25,0.26,4.0,709,No,1
24.0,female,Master,14283.0,1,MORTGAGE,1750.0,EDUCATION,10.99,0.12,2.0,679,No,1
25.0,male,Bachelor,195718.0,0,RENT,35000.0,VENTURE,7.49,0.18,4.0,684,Yes,0
25.0,male,High School,165792.0,4,RENT,34800.0,PERSONAL,16.77,0.21,2.0,662,No,0
22.0,female,Master,79255.0,0,RENT,34000.0,EDUCATION,17.58,0.43,4.0,691,No,1
24.0,female,Bachelor,13866.0,0,OWN,1500.0,PERSONAL,7.29,0.11,3.0,600,Yes,0
22.0,male,Bachelor,97420.0,1,RENT,33950.0,PERSONAL,14.54,0.35,4.0,691,No,1
24.0,female,High School,82443.0,0,RENT,33000.0,HOMEIMPROVEMENT,12.68,0.4,3.0,654,No,1
21.0,female,Associate,14288.0,0,MORTGAGE,4575.0,VENTURE,17.74,0.32,3.0,626,No,1
23.0,male,High School,14293.0,0,OWN,1400.0,PERSONAL,9.32,0.1,3.0,607,No,0
24.0,female,Bachelor,79054.0,1,RENT,32500.0,HOMEIMPROVEMENT,9.99,0.41,3.0,700,No,1
21.0,female,Bachelor,14988.0,0,OTHER,4000.0,EDUCATION,12.84,0.27,2.0,553,No,1
21.0,male,High School,14858.0,0,OWN,2000.0,MEDICAL,11.12,0.13,3.0,589,No,1
25.0,male,Bachelor,144855.0,1,RENT,32000.0,VENTURE,6.62,0.22,2.0,586,Yes,0
26.0,male,Bachelor,114645.0,2,RENT,31050.0,HOMEIMPROVEMENT,14.17,0.27,3.0,681,No,1
25.0,female,High School,368115.0,3,RENT,24250.0,DEBTCONSOLIDATION,13.85,0.07,3.0,567,Yes,0
26.0,female,Associate,361076.0,1,MORTGAGE,7800.0,MEDICAL,13.49,0.02,4.0,669,No,0
21.0,male,Associate,15150.0,0,OWN,2500.0,EDUCATION,7.51,0.17,4.0,600,No,1
22.0,female,Bachelor,58868.0,0,RENT,30000.0,EDUCATION,18.39,0.51,2.0,606,No,1
24.0,male,High School,78026.0,3,RENT,30000.0,DEBTCONSOLIDATION,14.54,0.38,3.0,582,No,1
25.0,male,Bachelor,90785.0,4,RENT,30000.0,HOMEIMPROVEMENT,16.89,0.33,4.0,649,No,1
23.0,female,High School,86811.0,0,RENT,30000.0,DEBTCONSOLIDATION,11.01,0.35,4.0,602,No,1
26.0,male,Bachelor,75503.0,5,RENT,30000.0,MEDICAL,17.99,0.4,2.0,616,No,1
24.0,female,High School,15082.0,0,OWN,2500.0,VENTURE,12.69,0.17,3.0,631,No,1
26.0,male,Bachelor,361293.0,5,MORTGAGE,20000.0,VENTURE,7.88,0.06,4.0,684,Yes,0
23.0,male,High School,361547.0,0,OWN,24250.0,EDUCATION,19.41,0.07,2.0,637,Yes,0
26.0,male,Master,360680.0,5,OWN,10000.0,HOMEIMPROVEMENT,10.38,0.03,4.0,649,No,0
26.0,male,Bachelor,360977.0,5,MORTGAGE,25000.0,EDUCATION,15.33,0.07,3.0,695,Yes,0
25.0,female,Bachelor,361244.0,2,MORTGAGE,18000.0,HOMEIMPROVEMENT,16.45,0.05,3.0,620,No,0
26.0,male,Bachelor,98230.0,2,RENT,30000.0,PERSONAL,7.49,0.31,3.0,622,No,1
22.0,female,High School,80838.0,0,RENT,30000.0,MEDICAL,12.69,0.37,3.0,645,No,1
26.0,male,Master,107957.0,2,RENT,30000.0,DEBTCONSOLIDATION,6.62,0.28,3.0,654,No,1
24.0,female,Bachelor,94649.0,2,RENT,30000.0,DEBTCONSOLIDATION,11.01,0.32,4.0,624,No,1
23.0,male,High School,94550.0,1,RENT,30000.0,DEBTCONSOLIDATION,18.62,0.32,3.0,570,No,1
23.0,male,Bachelor,111153.0,3,RENT,30000.0,PERSONAL,15.23,0.27,3.0,648,No,1
23.0,female,Associate,117250.0,0,RENT,30000.0,VENTURE,10.65,0.26,2.0,652,No,1
25.0,male,Bachelor,144985.0,3,RENT,30000.0,EDUCATION,7.9,0.21,4.0,559,No,0
26.0,male,High School,337133.0,7,RENT,10000.0,PERSONAL,15.96,0.03,3.0,623,Yes,0
26.0,male,Associate,333566.0,2,RENT,20000.0,VENTURE,11.48,0.06,3.0,602,Yes,0
23.0,male,Bachelor,333399.0,1,OWN,35000.0,PERSONAL,11.01,0.1,4.0,609,No,0
25.0,male,Master,154793.0,1,RENT,30000.0,PERSONAL,7.29,0.19,4.0,573,Yes,0
24.0,male,Associate,15229.0,1,OWN,1750.0,VENTURE,11.01,0.11,3.0,631,Yes,0
21.0,female,Bachelor,158338.0,0,RENT,30000.0,VENTURE,5.99,0.19,4.0,623,Yes,0
22.0,female,Bachelor,331034.0,0,OWN,12000.0,VENTURE,11.58,0.04,2.0,602,Yes,0
26.0,female,High School,316466.0,6,MORTGAGE,10000.0,EDUCATION,11.01,0.03,4.0,579,No,1
25.0,female,Associate,267671.0,0,MORTGAGE,25000.0,MEDICAL,15.7,0.09,2.0,582,No,1
22.0,male,Master,85191.0,0,RENT,29100.0,EDUCATION,15.99,0.34,3.0,700,No,1
22.0,male,Associate,15013.0,0,MORTGAGE,1500.0,EDUCATION,14.84,0.1,3.0,688,No,0
26.0,male,Bachelor,313100.0,3,OWN,28000.0,HOMEIMPROVEMENT,10.99,0.09,3.0,607,Yes,0
25.0,female,Bachelor,311952.0,0,MORTGAGE,20000.0,HOMEIMPROVEMENT,14.42,0.06,2.0,661,Yes,0
24.0,male,High School,306897.0,5,MORTGAGE,9600.0,EDUCATION,6.99,0.03,2.0,562,Yes,0
25.0,female,Bachelor,301136.0,0,RENT,25000.0,MEDICAL,13.49,0.08,4.0,664,Yes,0
25.0,male,High School,15162.0,1,OWN,3000.0,MEDICAL,11.01,0.2,3.0,564,No,1
22.0,male,Associate,69042.0,0,RENT,28000.0,MEDICAL,11.01,0.41,2.0,598,No,1
21.0,female,High School,15307.0,0,OWN,3000.0,EDUCATION,13.61,0.2,3.0,557,No,1
23.0,female,Associate,79183.0,0,RENT,28000.0,EDUCATION,7.9,0.35,2.0,677,No,1
26.0,male,Bachelor,102654.0,4,RENT,28000.0,VENTURE,7.49,0.27,3.0,690,No,1
26.0,male,Associate,15229.0,1,OWN,6100.0,EDUCATION,7.51,0.4,3.0,599,No,1
22.0,male,High School,106566.0,0,RENT,28000.0,VENTURE,9.91,0.26,3.0,604,No,1
21.0,female,Bachelor,15252.0,0,OWN,4200.0,PERSONAL,13.48,0.28,4.0,663,No,1
22.0,male,Bachelor,15432.0,3,OWN,4750.0,DEBTCONSOLIDATION,7.14,0.31,2.0,601,No,1
24.0,male,High School,100332.0,1,RENT,28000.0,VENTURE,15.99,0.28,4.0,634,No,1
24.0,male,Bachelor,300951.0,2,RENT,18000.0,EDUCATION,12.98,0.06,3.0,671,No,0
144.0,male,Bachelor,300616.0,125,RENT,4800.0,VENTURE,13.57,0.02,3.0,789,No,0
25.0,female,Bachelor,121062.0,1,RENT,28000.0,DEBTCONSOLIDATION,12.69,0.23,3.0,622,No,0
26.0,male,Associate,133372.0,1,RENT,28000.0,EDUCATION,8.9,0.21,2.0,538,Yes,0
26.0,male,Bachelor,15505.0,0,OWN,2700.0,DEBTCONSOLIDATION,11.01,0.17,4.0,587,No,1
22.0,male,Master,130852.0,0,RENT,28000.0,EDUCATION,11.01,0.21,4.0,683,No,1
23.0,male,Associate,182316.0,0,RENT,28000.0,DEBTCONSOLIDATION,11.11,0.15,2.0,634,Yes,0
24.0,female,Bachelor,83853.0,3,RENT,27600.0,HOMEIMPROVEMENT,11.01,0.33,2.0,690,No,1
21.0,female,Bachelor,15394.0,0,MORTGAGE,3250.0,DEBTCONSOLIDATION,15.68,0.21,3.0,518,No,1
22.0,female,Bachelor,85243.0,0,RENT,27500.0,EDUCATION,13.06,0.32,3.0,583,No,1
22.0,male,Associate,288907.0,2,OWN,25000.0,PERSONAL,11.01,0.09,2.0,617,Yes,0
26.0,male,Associate,89074.0,4,RENT,27050.0,VENTURE,15.62,0.3,2.0,668,No,1
24.0,male,Master,100509.0,2,RENT,27000.0,PERSONAL,13.49,0.27,2.0,673,No,1
24.0,male,High School,88950.0,3,RENT,27000.0,VENTURE,11.01,0.3,3.0,706,No,1
23.0,female,High School,75894.0,1,RENT,26000.0,MEDICAL,11.71,0.34,2.0,536,No,1
23.0,male,Associate,145092.0,0,RENT,25600.0,EDUCATION,12.69,0.18,3.0,557,Yes,0
24.0,female,Bachelor,15928.0,1,OWN,1600.0,MEDICAL,13.57,0.1,3.0,689,Yes,0
22.0,male,Bachelor,73131.0,3,RENT,25475.0,VENTURE,10.99,0.35,3.0,681,No,1
25.0,male,Master,281501.0,4,MORTGAGE,20000.0,MEDICAL,14.27,0.07,4.0,623,Yes,0
24.0,female,Associate,281775.0,0,OWN,20000.0,HOMEIMPROVEMENT,8.88,0.07,4.0,595,Yes,0

In [6]:
# Build payload text step by step.
# Payload text is a short profile of the dataset.
# It is safer and smaller than sending the full dataset to the LLM.

payload_text = ''

# 1. Shape
payload_text += '=== SHAPE ===\n'
payload_text += 'Rows: ' + str(df.shape[0]) + '\n' #[1000,15]
payload_text += 'Columns: ' + str(df.shape[1]) + '\n\n'

# 2. Column names and data types
payload_text += '=== COLUMNS AND DATA TYPES ===\n'
payload_text += df.dtypes.to_string()
payload_text += '\n\n'

# 3. Numeric summary
payload_text += "=== NUMERIC SUMMARY ===\n"
num_cols = df.select_dtypes(include=["number"]).columns
if len(num_cols) > 0:
    numeric_summary = df[num_cols].describe().round(2)
    payload_text += numeric_summary.to_string()
else:
    payload_text += "No numeric columns found."
payload_text += "\n\n"

# 4. categorical describe
payload_text += "=== CATEGORICAL DESCRIBE ===\n"
cat_cols = df.select_dtypes(include=["object", "category"]).columns
if len(cat_cols) > 0:
    categorical_summary = df[cat_cols].describe()
    payload_text += categorical_summary.to_string()
else:
    payload_text += "No categorical columns found."
payload_text += "\n\n"

# 5. Missing values
payload_text += '=== MISSING VALUES ===\n'
missing_table = pd.DataFrame()
missing_table['missing_count'] = df.isna().sum()
missing_table['missing_pct'] = (df.isna().sum() / len(df) * 100).round(2)
payload_text += missing_table.to_string()
payload_text += '\n\n'

# 6. outlier summary
payload_text += "=== OUTLIER SUMMARY (IQR METHOD) ===\n"

if len(num_cols) > 0:

    Q1 = df[num_cols].quantile(0.25)
    Q3 = df[num_cols].quantile(0.75)
    IQR = Q3 - Q1

    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR

    outliers = (
        (df[num_cols] < lower_bound) |
        (df[num_cols] > upper_bound)
    ).sum()

    outlier_pct = (
        outliers / len(df) * 100
    ).round(2)

    outlier_table = pd.DataFrame({
        "outlier_count": outliers,
        "outlier_pct": outlier_pct
    })

    payload_text += outlier_table.to_string()

else:
    payload_text += "No numeric columns found."

payload_text += "\n\n"

# 7. Unique values per column
payload_text += '=== UNIQUE VALUES PER COLUMN ===\n'
unique_table = pd.DataFrame()
unique_table['unique_count'] = df.nunique(dropna=False)
payload_text += unique_table.to_string()
payload_text += '\n\n'

# 8. Correlation between numeric columns
payload_text += '=== CORRELATION BETWEEN NUMERIC COLUMNS ===\n'
correlation_table = df.corr(numeric_only=True).round(2)
payload_text += correlation_table.to_string()
payload_text += '\n\n'

# 9. Top 10 values for categorical columns
payload_text += '=== TOP 10 VALUES FOR CATEGORICAL COLUMNS ===\n'

categorical_columns = df.select_dtypes(include=['object', 'category']).columns.tolist()

if len(categorical_columns) == 0:
    payload_text += 'No categorical columns found.\n'
else:
    for col in categorical_columns:
        payload_text += '\nColumn: ' + col + '\n'
        payload_text += df[col].value_counts(dropna=False).head(10).to_string()
        payload_text += '\n'

payload_text += '\n'

# 10. Simple warning checks
payload_text += '=== SIMPLE WARNING CHECKS ===\n'

id_like_columns = []
constant_columns = []

for col in df.columns:
    unique_count = df[col].nunique(dropna=False)

    if unique_count == len(df):
        id_like_columns.append(col)

    if unique_count <= 1:
        constant_columns.append(col)

payload_text += 'Possible ID-like columns: ' + str(id_like_columns) + '\n'
payload_text += 'Constant columns: ' + str(constant_columns) + '\n'
payload_text += 'Duplicate rows: ' + str(df.duplicated().sum()) + '\n'

print(payload_text)

# This cell builds a short dataset profile called payload_text.
# Instead of sending the full dataset to the LLM, we send summary information only.
# The payload includes shape, column types, numeric summary, missing values, unique counts, correlations, and common category values.
# It also adds simple warning checks for possible ID-like columns, constant columns, and duplicate rows.
# This helps the LLM comment on data readiness without needing every row of the dataset.

=== SHAPE ===
Rows: 45000
Columns: 14

=== COLUMNS AND DATA TYPES ===
person_age                        float64
person_gender                      object
person_education                   object
person_income                     float64
person_emp_exp                      int64
person_home_ownership              object
loan_amnt                         float64
loan_intent                        object
loan_int_rate                     float64
loan_percent_income               float64
cb_person_cred_hist_length        float64
credit_score                        int64
previous_loan_defaults_on_file     object
loan_status                         int64

=== NUMERIC SUMMARY ===
       person_age  person_income  person_emp_exp  loan_amnt  loan_int_rate  loan_percent_income  cb_person_cred_hist_length  credit_score  loan_status
count    45000.00       45000.00        45000.00   45000.00       45000.00             45000.00                    45000.00      45000.00     45000.00
mean        27.76       80319.05            5.41    9583.16          11.01                 0.14                        5.87        632.61         0.22
std          6.05       80422.50            6.06    6314.89           2.98                 0.09                        3.88         50.44         0.42
min         20.00        8000.00            0.00     500.00           5.42                 0.00                        2.00        390.00         0.00
25%         24.00       47204.00            1.00    5000.00           8.59                 0.07                        3.00        601.00         0.00
50%         26.00       67048.00            4.00    8000.00          11.01                 0.12                        4.00        640.00         0.00
75%         30.00       95789.25            8.00   12237.25          12.99                 0.19                        8.00        670.00         0.00
max        144.00     7200766.00          125.00   35000.00          20.00                 0.66                       30.00        850.00         1.00

=== CATEGORICAL DESCRIBE ===
       person_gender person_education person_home_ownership loan_intent previous_loan_defaults_on_file
count          45000            45000                 45000       45000                          45000
unique             2                5                     4           6                              2
top             male         Bachelor                  RENT   EDUCATION                            Yes
freq           24841            13399                 23443        9153                          22858

=== MISSING VALUES ===
                                missing_count  missing_pct
person_age                                  0          0.0
person_gender                               0          0.0
person_education                            0          0.0
person_income                               0          0.0
person_emp_exp                              0          0.0
person_home_ownership                       0          0.0
loan_amnt                                   0          0.0
loan_intent                                 0          0.0
loan_int_rate                               0          0.0
loan_percent_income                         0          0.0
cb_person_cred_hist_length                  0          0.0
credit_score                                0          0.0
previous_loan_defaults_on_file              0          0.0
loan_status                                 0          0.0

=== OUTLIER SUMMARY (IQR METHOD) ===
                            outlier_count  outlier_pct
person_age                           2188         4.86
person_income                        2218         4.93
person_emp_exp                       1724         3.83
loan_amnt                            2348         5.22
loan_int_rate                         124         0.28
loan_percent_income                   744         1.65
cb_person_cred_hist_length           1366         3.04
credit_score                          467         1.04
loan_status                         10000        22.22

=== UNIQUE VALUES PER COLUMN ===
                                unique_count
person_age                                60
person_gender                              2
person_education                           5
person_income                          33989
person_emp_exp                            63
person_home_ownership                      4
loan_amnt                               4483
loan_intent                                6
loan_int_rate                           1302
loan_percent_income                       64
cb_person_cred_hist_length                29
credit_score                             340
previous_loan_defaults_on_file             2
loan_status                                2

=== CORRELATION BETWEEN NUMERIC COLUMNS ===
                            person_age  person_income  person_emp_exp  loan_amnt  loan_int_rate  loan_percent_income  cb_person_cred_hist_length  credit_score  loan_status
person_age                        1.00           0.19            0.95       0.05           0.01                -0.04                        0.86          0.18        -0.02
person_income                     0.19           1.00            0.19       0.24           0.00                -0.23                        0.12          0.04        -0.14
person_emp_exp                    0.95           0.19            1.00       0.04           0.02                -0.04                        0.82          0.19        -0.02
loan_amnt                         0.05           0.24            0.04       1.00           0.15                 0.59                        0.04          0.01         0.11
loan_int_rate                     0.01           0.00            0.02       0.15           1.00                 0.13                        0.02          0.01         0.33
loan_percent_income              -0.04          -0.23           -0.04       0.59           0.13                 1.00                       -0.03         -0.01         0.38
cb_person_cred_hist_length        0.86           0.12            0.82       0.04           0.02                -0.03                        1.00          0.16        -0.01
credit_score                      0.18           0.04            0.19       0.01           0.01                -0.01                        0.16          1.00        -0.01
loan_status                      -0.02          -0.14           -0.02       0.11           0.33                 0.38                       -0.01         -0.01         1.00

=== TOP 10 VALUES FOR CATEGORICAL COLUMNS ===

Column: person_gender
person_gender
male      24841
female    20159

Column: person_education
person_education
Bachelor       13399
Associate      12028
High School    11972
Master          6980
Doctorate        621

Column: person_home_ownership
person_home_ownership
RENT        23443
MORTGAGE    18489
OWN          2951
OTHER         117

Column: loan_intent
loan_intent
EDUCATION            9153
MEDICAL              8548
VENTURE              7819
PERSONAL             7552
DEBTCONSOLIDATION    7145
HOMEIMPROVEMENT      4783

Column: previous_loan_defaults_on_file
previous_loan_defaults_on_file
Yes    22858
No     22142

=== SIMPLE WARNING CHECKS ===
Possible ID-like columns: []
Constant columns: []
Duplicate rows: 0

In [6]:
prompt_dataset = f"""

You are an expert data scientist with experience in tree-based regression models.
Here are the first 100 rows of a dataset:\n{data_preview}\n\n
Dataset info: \n{payload_text}\n

Dataset context: The dataset contains loan approval, indicating whether an applicant is likely to be approved or denied for a loan with various demographic and financial features.

Please answer:

1) What should the Business problem be?
2) What should the modelling objective be?
3) What is the most meaningful target column?
4) Which metric would be easiest to explain to business users?
5) Who are the main stakeholders?
6) What are three risks or pitfalls?

Keep the answer concise.
Do not invent causes.
Do not overclaim.

"""

print('Prompt to send:')
print(prompt_dataset)

if client is not None:
    response = client.responses.create(
        model=OPENAI_MODEL,
        input=prompt_dataset
    )
    print('\nLLM response:')
    print(response.output_text)
else:
    print('\nNo API response because client is not connected. Copy the prompt above into your chatbot.')

# This cell creates a prompt for the LLM using the first 10 rows of the dataset.
# The f-string allows Python to insert data_preview directly into the prompt text.
# The prompt asks the LLM to inspect the dataset and give simple modelling-readiness comments.
# preview_prompt[:2000] prints only the first 2000 characters so the output is not too long.
# If client is connected, the prompt is sent to the OpenAI API using the selected model.
# response.output_text prints the LLM's answer in the notebook.
# If client is not connected, students can copy the printed prompt and paste it into ChatGPT manually.

Prompt to send:


You are an expert data scientist with experience in tree-based regression models.
Here are the first 100 rows of a dataset:
person_age,person_gender,person_education,person_income,person_emp_exp,person_home_ownership,loan_amnt,loan_intent,loan_int_rate,loan_percent_income,cb_person_cred_hist_length,credit_score,previous_loan_defaults_on_file,loan_status
22.0,female,Master,71948.0,0,RENT,35000.0,PERSONAL,16.02,0.49,3.0,561,No,1
21.0,female,High School,12282.0,0,OWN,1000.0,EDUCATION,11.14,0.08,2.0,504,Yes,0
25.0,female,High School,12438.0,3,MORTGAGE,5500.0,MEDICAL,12.87,0.44,3.0,635,No,1
23.0,female,Bachelor,79753.0,0,RENT,35000.0,MEDICAL,15.23,0.44,2.0,675,No,1
24.0,male,Master,66135.0,1,RENT,35000.0,MEDICAL,14.27,0.53,4.0,586,No,1
21.0,female,High School,12951.0,0,OWN,2500.0,VENTURE,7.14,0.19,2.0,532,No,1
26.0,female,Bachelor,93471.0,1,RENT,35000.0,EDUCATION,12.42,0.37,3.0,701,No,1
24.0,female,High School,95550.0,5,RENT,35000.0,MEDICAL,11.11,0.37,4.0,585,No,1
24.0,female,Associate,100684.0,3,RENT,35000.0,PERSONAL,8.9,0.35,2.0,544,No,1
21.0,female,High School,12739.0,0,OWN,1600.0,VENTURE,14.74,0.13,3.0,640,No,1
22.0,female,High School,102985.0,0,RENT,35000.0,VENTURE,10.37,0.34,4.0,621,No,1
21.0,female,Associate,13113.0,0,OWN,4500.0,HOMEIMPROVEMENT,8.63,0.34,2.0,651,No,1
23.0,male,Bachelor,114860.0,3,RENT,35000.0,VENTURE,7.9,0.3,2.0,573,No,1
26.0,male,Master,130713.0,0,RENT,35000.0,EDUCATION,18.39,0.27,4.0,708,No,1
23.0,female,Associate,138998.0,0,RENT,35000.0,EDUCATION,7.9,0.25,4.0,583,No,0
23.0,female,Master,600891.0,5,MORTGAGE,30000.0,DEBTCONSOLIDATION,10.65,0.05,3.0,670,Yes,0
23.0,male,Bachelor,144943.0,0,RENT,35000.0,EDUCATION,7.9,0.24,4.0,663,No,0
23.0,female,High School,111369.0,0,RENT,35000.0,MEDICAL,20.0,0.31,4.0,694,No,1
23.0,male,Bachelor,136628.0,0,RENT,35000.0,DEBTCONSOLIDATION,18.25,0.26,4.0,709,No,1
24.0,female,Master,14283.0,1,MORTGAGE,1750.0,EDUCATION,10.99,0.12,2.0,679,No,1
25.0,male,Bachelor,195718.0,0,RENT,35000.0,VENTURE,7.49,0.18,4.0,684,Yes,0
25.0,male,High School,165792.0,4,RENT,34800.0,PERSONAL,16.77,0.21,2.0,662,No,0
22.0,female,Master,79255.0,0,RENT,34000.0,EDUCATION,17.58,0.43,4.0,691,No,1
24.0,female,Bachelor,13866.0,0,OWN,1500.0,PERSONAL,7.29,0.11,3.0,600,Yes,0
22.0,male,Bachelor,97420.0,1,RENT,33950.0,PERSONAL,14.54,0.35,4.0,691,No,1
24.0,female,High School,82443.0,0,RENT,33000.0,HOMEIMPROVEMENT,12.68,0.4,3.0,654,No,1
21.0,female,Associate,14288.0,0,MORTGAGE,4575.0,VENTURE,17.74,0.32,3.0,626,No,1
23.0,male,High School,14293.0,0,OWN,1400.0,PERSONAL,9.32,0.1,3.0,607,No,0
24.0,female,Bachelor,79054.0,1,RENT,32500.0,HOMEIMPROVEMENT,9.99,0.41,3.0,700,No,1
21.0,female,Bachelor,14988.0,0,OTHER,4000.0,EDUCATION,12.84,0.27,2.0,553,No,1
21.0,male,High School,14858.0,0,OWN,2000.0,MEDICAL,11.12,0.13,3.0,589,No,1
25.0,male,Bachelor,144855.0,1,RENT,32000.0,VENTURE,6.62,0.22,2.0,586,Yes,0
26.0,male,Bachelor,114645.0,2,RENT,31050.0,HOMEIMPROVEMENT,14.17,0.27,3.0,681,No,1
25.0,female,High School,368115.0,3,RENT,24250.0,DEBTCONSOLIDATION,13.85,0.07,3.0,567,Yes,0
26.0,female,Associate,361076.0,1,MORTGAGE,7800.0,MEDICAL,13.49,0.02,4.0,669,No,0
21.0,male,Associate,15150.0,0,OWN,2500.0,EDUCATION,7.51,0.17,4.0,600,No,1
22.0,female,Bachelor,58868.0,0,RENT,30000.0,EDUCATION,18.39,0.51,2.0,606,No,1
24.0,male,High School,78026.0,3,RENT,30000.0,DEBTCONSOLIDATION,14.54,0.38,3.0,582,No,1
25.0,male,Bachelor,90785.0,4,RENT,30000.0,HOMEIMPROVEMENT,16.89,0.33,4.0,649,No,1
23.0,female,High School,86811.0,0,RENT,30000.0,DEBTCONSOLIDATION,11.01,0.35,4.0,602,No,1
26.0,male,Bachelor,75503.0,5,RENT,30000.0,MEDICAL,17.99,0.4,2.0,616,No,1
24.0,female,High School,15082.0,0,OWN,2500.0,VENTURE,12.69,0.17,3.0,631,No,1
26.0,male,Bachelor,361293.0,5,MORTGAGE,20000.0,VENTURE,7.88,0.06,4.0,684,Yes,0
23.0,male,High School,361547.0,0,OWN,24250.0,EDUCATION,19.41,0.07,2.0,637,Yes,0
26.0,male,Master,360680.0,5,OWN,10000.0,HOMEIMPROVEMENT,10.38,0.03,4.0,649,No,0
26.0,male,Bachelor,360977.0,5,MORTGAGE,25000.0,EDUCATION,15.33,0.07,3.0,695,Yes,0
25.0,female,Bachelor,361244.0,2,MORTGAGE,18000.0,HOMEIMPROVEMENT,16.45,0.05,3.0,620,No,0
26.0,male,Bachelor,98230.0,2,RENT,30000.0,PERSONAL,7.49,0.31,3.0,622,No,1
22.0,female,High School,80838.0,0,RENT,30000.0,MEDICAL,12.69,0.37,3.0,645,No,1
26.0,male,Master,107957.0,2,RENT,30000.0,DEBTCONSOLIDATION,6.62,0.28,3.0,654,No,1
24.0,female,Bachelor,94649.0,2,RENT,30000.0,DEBTCONSOLIDATION,11.01,0.32,4.0,624,No,1
23.0,male,High School,94550.0,1,RENT,30000.0,DEBTCONSOLIDATION,18.62,0.32,3.0,570,No,1
23.0,male,Bachelor,111153.0,3,RENT,30000.0,PERSONAL,15.23,0.27,3.0,648,No,1
23.0,female,Associate,117250.0,0,RENT,30000.0,VENTURE,10.65,0.26,2.0,652,No,1
25.0,male,Bachelor,144985.0,3,RENT,30000.0,EDUCATION,7.9,0.21,4.0,559,No,0
26.0,male,High School,337133.0,7,RENT,10000.0,PERSONAL,15.96,0.03,3.0,623,Yes,0
26.0,male,Associate,333566.0,2,RENT,20000.0,VENTURE,11.48,0.06,3.0,602,Yes,0
23.0,male,Bachelor,333399.0,1,OWN,35000.0,PERSONAL,11.01,0.1,4.0,609,No,0
25.0,male,Master,154793.0,1,RENT,30000.0,PERSONAL,7.29,0.19,4.0,573,Yes,0
24.0,male,Associate,15229.0,1,OWN,1750.0,VENTURE,11.01,0.11,3.0,631,Yes,0
21.0,female,Bachelor,158338.0,0,RENT,30000.0,VENTURE,5.99,0.19,4.0,623,Yes,0
22.0,female,Bachelor,331034.0,0,OWN,12000.0,VENTURE,11.58,0.04,2.0,602,Yes,0
26.0,female,High School,316466.0,6,MORTGAGE,10000.0,EDUCATION,11.01,0.03,4.0,579,No,1
25.0,female,Associate,267671.0,0,MORTGAGE,25000.0,MEDICAL,15.7,0.09,2.0,582,No,1
22.0,male,Master,85191.0,0,RENT,29100.0,EDUCATION,15.99,0.34,3.0,700,No,1
22.0,male,Associate,15013.0,0,MORTGAGE,1500.0,EDUCATION,14.84,0.1,3.0,688,No,0
26.0,male,Bachelor,313100.0,3,OWN,28000.0,HOMEIMPROVEMENT,10.99,0.09,3.0,607,Yes,0
25.0,female,Bachelor,311952.0,0,MORTGAGE,20000.0,HOMEIMPROVEMENT,14.42,0.06,2.0,661,Yes,0
24.0,male,High School,306897.0,5,MORTGAGE,9600.0,EDUCATION,6.99,0.03,2.0,562,Yes,0
25.0,female,Bachelor,301136.0,0,RENT,25000.0,MEDICAL,13.49,0.08,4.0,664,Yes,0
25.0,male,High School,15162.0,1,OWN,3000.0,MEDICAL,11.01,0.2,3.0,564,No,1
22.0,male,Associate,69042.0,0,RENT,28000.0,MEDICAL,11.01,0.41,2.0,598,No,1
21.0,female,High School,15307.0,0,OWN,3000.0,EDUCATION,13.61,0.2,3.0,557,No,1
23.0,female,Associate,79183.0,0,RENT,28000.0,EDUCATION,7.9,0.35,2.0,677,No,1
26.0,male,Bachelor,102654.0,4,RENT,28000.0,VENTURE,7.49,0.27,3.0,690,No,1
26.0,male,Associate,15229.0,1,OWN,6100.0,EDUCATION,7.51,0.4,3.0,599,No,1
22.0,male,High School,106566.0,0,RENT,28000.0,VENTURE,9.91,0.26,3.0,604,No,1
21.0,female,Bachelor,15252.0,0,OWN,4200.0,PERSONAL,13.48,0.28,4.0,663,No,1
22.0,male,Bachelor,15432.0,3,OWN,4750.0,DEBTCONSOLIDATION,7.14,0.31,2.0,601,No,1
24.0,male,High School,100332.0,1,RENT,28000.0,VENTURE,15.99,0.28,4.0,634,No,1
24.0,male,Bachelor,300951.0,2,RENT,18000.0,EDUCATION,12.98,0.06,3.0,671,No,0
144.0,male,Bachelor,300616.0,125,RENT,4800.0,VENTURE,13.57,0.02,3.0,789,No,0
25.0,female,Bachelor,121062.0,1,RENT,28000.0,DEBTCONSOLIDATION,12.69,0.23,3.0,622,No,0
26.0,male,Associate,133372.0,1,RENT,28000.0,EDUCATION,8.9,0.21,2.0,538,Yes,0
26.0,male,Bachelor,15505.0,0,OWN,2700.0,DEBTCONSOLIDATION,11.01,0.17,4.0,587,No,1
22.0,male,Master,130852.0,0,RENT,28000.0,EDUCATION,11.01,0.21,4.0,683,No,1
23.0,male,Associate,182316.0,0,RENT,28000.0,DEBTCONSOLIDATION,11.11,0.15,2.0,634,Yes,0
24.0,female,Bachelor,83853.0,3,RENT,27600.0,HOMEIMPROVEMENT,11.01,0.33,2.0,690,No,1
21.0,female,Bachelor,15394.0,0,MORTGAGE,3250.0,DEBTCONSOLIDATION,15.68,0.21,3.0,518,No,1
22.0,female,Bachelor,85243.0,0,RENT,27500.0,EDUCATION,13.06,0.32,3.0,583,No,1
22.0,male,Associate,288907.0,2,OWN,25000.0,PERSONAL,11.01,0.09,2.0,617,Yes,0
26.0,male,Associate,89074.0,4,RENT,27050.0,VENTURE,15.62,0.3,2.0,668,No,1
24.0,male,Master,100509.0,2,RENT,27000.0,PERSONAL,13.49,0.27,2.0,673,No,1
24.0,male,High School,88950.0,3,RENT,27000.0,VENTURE,11.01,0.3,3.0,706,No,1
23.0,female,High School,75894.0,1,RENT,26000.0,MEDICAL,11.71,0.34,2.0,536,No,1
23.0,male,Associate,145092.0,0,RENT,25600.0,EDUCATION,12.69,0.18,3.0,557,Yes,0
24.0,female,Bachelor,15928.0,1,OWN,1600.0,MEDICAL,13.57,0.1,3.0,689,Yes,0
22.0,male,Bachelor,73131.0,3,RENT,25475.0,VENTURE,10.99,0.35,3.0,681,No,1
25.0,male,Master,281501.0,4,MORTGAGE,20000.0,MEDICAL,14.27,0.07,4.0,623,Yes,0
24.0,female,Associate,281775.0,0,OWN,20000.0,HOMEIMPROVEMENT,8.88,0.07,4.0,595,Yes,0



Dataset info:
=== SHAPE ===
Rows: 45000
Columns: 14

=== COLUMNS AND DATA TYPES ===
person_age                        float64
person_gender                      object
person_education                   object
person_income                     float64
person_emp_exp                      int64
person_home_ownership              object
loan_amnt                         float64
loan_intent                        object
loan_int_rate                     float64
loan_percent_income               float64
cb_person_cred_hist_length        float64
credit_score                        int64
previous_loan_defaults_on_file     object
loan_status                         int64

=== NUMERIC SUMMARY ===
       person_age  person_income  person_emp_exp  loan_amnt  loan_int_rate  loan_percent_income  cb_person_cred_hist_length  credit_score  loan_status
count    45000.00       45000.00        45000.00   45000.00       45000.00             45000.00                    45000.00      45000.00     45000.00
mean        27.76       80319.05            5.41    9583.16          11.01                 0.14                        5.87        632.61         0.22
std          6.05       80422.50            6.06    6314.89           2.98                 0.09                        3.88         50.44         0.42
min         20.00        8000.00            0.00     500.00           5.42                 0.00                        2.00        390.00         0.00
25%         24.00       47204.00            1.00    5000.00           8.59                 0.07                        3.00        601.00         0.00
50%         26.00       67048.00            4.00    8000.00          11.01                 0.12                        4.00        640.00         0.00
75%         30.00       95789.25            8.00   12237.25          12.99                 0.19                        8.00        670.00         0.00
max        144.00     7200766.00          125.00   35000.00          20.00                 0.66                       30.00        850.00         1.00

=== CATEGORICAL DESCRIBE ===
       person_gender person_education person_home_ownership loan_intent previous_loan_defaults_on_file
count          45000            45000                 45000       45000                          45000
unique             2                5                     4           6                              2
top             male         Bachelor                  RENT   EDUCATION                            Yes
freq           24841            13399                 23443        9153                          22858

=== MISSING VALUES ===
                                missing_count  missing_pct
person_age                                  0          0.0
person_gender                               0          0.0
person_education                            0          0.0
person_income                               0          0.0
person_emp_exp                              0          0.0
person_home_ownership                       0          0.0
loan_amnt                                   0          0.0
loan_intent                                 0          0.0
loan_int_rate                               0          0.0
loan_percent_income                         0          0.0
cb_person_cred_hist_length                  0          0.0
credit_score                                0          0.0
previous_loan_defaults_on_file              0          0.0
loan_status                                 0          0.0

=== OUTLIER SUMMARY (IQR METHOD) ===
                            outlier_count  outlier_pct
person_age                           2188         4.86
person_income                        2218         4.93
person_emp_exp                       1724         3.83
loan_amnt                            2348         5.22
loan_int_rate                         124         0.28
loan_percent_income                   744         1.65
cb_person_cred_hist_length           1366         3.04
credit_score                          467         1.04
loan_status                         10000        22.22

=== UNIQUE VALUES PER COLUMN ===
                                unique_count
person_age                                60
person_gender                              2
person_education                           5
person_income                          33989
person_emp_exp                            63
person_home_ownership                      4
loan_amnt                               4483
loan_intent                                6
loan_int_rate                           1302
loan_percent_income                       64
cb_person_cred_hist_length                29
credit_score                             340
previous_loan_defaults_on_file             2
loan_status                                2

=== CORRELATION BETWEEN NUMERIC COLUMNS ===
                            person_age  person_income  person_emp_exp  loan_amnt  loan_int_rate  loan_percent_income  cb_person_cred_hist_length  credit_score  loan_status
person_age                        1.00           0.19            0.95       0.05           0.01                -0.04                        0.86          0.18        -0.02
person_income                     0.19           1.00            0.19       0.24           0.00                -0.23                        0.12          0.04        -0.14
person_emp_exp                    0.95           0.19            1.00       0.04           0.02                -0.04                        0.82          0.19        -0.02
loan_amnt                         0.05           0.24            0.04       1.00           0.15                 0.59                        0.04          0.01         0.11
loan_int_rate                     0.01           0.00            0.02       0.15           1.00                 0.13                        0.02          0.01         0.33
loan_percent_income              -0.04          -0.23           -0.04       0.59           0.13                 1.00                       -0.03         -0.01         0.38
cb_person_cred_hist_length        0.86           0.12            0.82       0.04           0.02                -0.03                        1.00          0.16        -0.01
credit_score                      0.18           0.04            0.19       0.01           0.01                -0.01                        0.16          1.00        -0.01
loan_status                      -0.02          -0.14           -0.02       0.11           0.33                 0.38                       -0.01         -0.01         1.00

=== TOP 10 VALUES FOR CATEGORICAL COLUMNS ===

Column: person_gender
person_gender
male      24841
female    20159

Column: person_education
person_education
Bachelor       13399
Associate      12028
High School    11972
Master          6980
Doctorate        621

Column: person_home_ownership
person_home_ownership
RENT        23443
MORTGAGE    18489
OWN          2951
OTHER         117

Column: loan_intent
loan_intent
EDUCATION            9153
MEDICAL              8548
VENTURE              7819
PERSONAL             7552
DEBTCONSOLIDATION    7145
HOMEIMPROVEMENT      4783

Column: previous_loan_defaults_on_file
previous_loan_defaults_on_file
Yes    22858
No     22142

=== SIMPLE WARNING CHECKS ===
Possible ID-like columns: []
Constant columns: []
Duplicate rows: 0



Dataset context: The dataset contains loan approval, indicating whether an applicant is likely to be approved or denied for a loan with various demographic and financial features.

Please answer:

1) What should the Business problem be?
2) What should the modelling objective be?
3) What is the most meaningful target column?
4) Which metric would be easiest to explain to business users?
5) Who are the main stakeholders?
6) What are three risks or pitfalls?

Keep the answer concise.
Do not invent causes.
Do not overclaim.



LLM response:
1) **Business problem**
Predict whether a loan application will be **approved or denied** so the lender can make more consistent, data-driven decisions and reduce unnecessary approvals/denials.

2) **Modelling objective**
Train a model to estimate **the probability of approval** (or denial) from applicant and loan attributes, to support underwriting decisioning and portfolio risk management.

3) **Most meaningful target column**
**`loan_status`** (binary: 1/0). This is the dataset’s explicit approval/denial outcome.

4) **Easiest metric to explain to business users**
**ROC-AUC** or **Accuracy** can be explained simply, but **AUC/accuracy may hide tradeoffs**. If you must pick one most broadly understandable: **Precision/Recall for the “approved” class** (or equivalently, recall/precision for the “denied” class) is typically easiest to map to business outcomes.
*(If forced to choose a single scalar: **AUC** is usually the simplest summary.)*

5) **Main stakeholders**
- Underwriting / credit risk teams
- Product / lending operations (decision workflow owners)
- Compliance / legal / fairness oversight
- Data science / model risk management
- Senior management (portfolio performance oversight)

6) **Three risks or pitfalls**
- **Class imbalance / decision tradeoffs:** With `loan_status` not evenly distributed, a single metric (e.g., accuracy) may be misleading—different error costs matter.
- **Outliers / data quality issues:** Numeric extremes exist (e.g., very high `person_age`, extreme income/loan values), which can destabilize models if not handled appropriately.
- **Bias & compliance risk:** Using demographic features (e.g., `person_gender`) without fairness checks can create discriminatory outcomes and compliance violations.

If you share how “approval” vs “denial” is defined in `loan_status` (which value means approved), I can recommend the “approved” class for precision/recall explicitly.

In [ ]:
# Another way to build payload

from io import StringIO

buffer = StringIO()

buffer.write("=== SHAPE ===\n")
buffer.write(f"Rows: {df.shape[0]}, Columns: {df.shape[1]}\n\n")

buffer.write("=== DTYPES ===\n")
buffer.write(df.dtypes.to_string())
buffer.write("\n\n")

buffer.write("=== NUMERIC DESCRIBE ===\n")
buffer.write(df.describe().to_string())
buffer.write("\n\n")

buffer.write("=== CATEGORICAL DESCRIBE ===\n")
cat_cols = df.select_dtypes(include="object").columns.tolist()
if cat_cols:
    buffer.write(df[cat_cols].describe().to_string())
else:
    buffer.write("No categorical columns")
buffer.write("\n\n")

buffer.write("=== NULL SUMMARY ===\n")
null_summary = df.isna().sum().to_frame("null_count")
null_summary["null_pct"] = null_summary["null_count"] / len(df)
buffer.write(null_summary.to_string())
buffer.write("\n\n")

buffer.write("=== UNIQUE VALUES PER COLUMN ===\n")
buffer.write(df.nunique().to_frame("unique_count").to_string())
buffer.write("\n\n")

buffer.write("=== CORRELATIONS: NUMERIC ONLY ===\n")
buffer.write(df.corr(numeric_only=True).round(3).to_string())
buffer.write("\n\n")

buffer.write("=== POSSIBLE UNIQUE-ID COLUMNS ===\n")
unique_id_cols = df.columns[df.nunique() == len(df)].tolist()
buffer.write(str(unique_id_cols))
buffer.write("\n")

payload_text = buffer.getvalue()
print(payload_text)

### Scenario

The bank is experiencing a low loan business volume. This may limit lending business growth and reduce potential revenue from interest and other loan-related products. The issue affects the Sales and Lending teams, who are responsible for acquiring customers and growing the bank's loan portfolio. The organisation is exploring whether a predictive model can help identify suitable loan applicants more effectively to support sustainable lending growth.

In [9]:
scenario_prompt = f"""
You are an expert data scientist with experience in tree-based models.

Context (given):\n
Jayden, an sales and leanding team manager of a bank want to explore whether building
model to identify suitable loan applicants more effectively to support sustainable lending growth. \n

Please draft the following. \n

[Task]

1.Business problem
•	Describe the business problem you aim to address. Explain why it matters and who is affected. \n
2. Identify the key beneficiary and create a simple persona that captures details important for this project,
such as the person’s goals, pain points, behaviours and how they would use the solution. \n
3. Use the Job-To-Be-Done (JTBD) framework shape modelling objectives, State the job the user is trying to complete,
and define your target variable and likely predictors based on this job. \n

[Format]

Respond in paragraph form, using clear line breaks. Insert Blank line between key idea to improve readability
For each subject keep it to max 3 line

[Constraints]
Keep response concise and actionable
"""


if client is not None:
    response = client.responses.create(
        model=OPENAI_MODEL,
        input=scenario_prompt
    )
    print('\nLLM response:')
    print(response.output_text)
else:
    print('\nNo API response because client is not connected. Copy the prompt above into your chatbot.')

LLM response:
**1. Business problem**
We need a model to predict which loan applicants are suitable for approval, improving sustainable lending growth.
Better targeting reduces credit losses, manual review workload, and improves customer experience.
Affected: Jayden’s sales/loan team, credit risk officers, and applicants waiting for decisions.

**2. Key beneficiary & persona**
Primary beneficiary: Jayden, the sales and lending manager overseeing loan decisions and performance.
Persona: “Jayden” aims to balance growth with risk limits, reduce rework, and meet SLA targets.
He uses the tool during pipeline review to prioritize applications, justify decisions, and focus follow-ups.

**3. JTBD objectives, target & predictors**
Job-to-be-done: “Decide quickly and confidently which applicants should receive approval (or which need extra checks).”
Target variable: loan decision outcome such as default/repayment status or approval suitability label.
Likely predictors: application features (income, employment, tenure), credit bureau metrics, debt-to-income, loan amount/term, and prior repayment behavior.

In [8]:
quality_prompt = f"""
You are an expert data scientist with experience in tree-based regression models.
Here are the first 100 rows of a dataset:\n{data_preview}\n\n
Here is the dataset profile:\n{payload_text}\n\n

Insight found:
1. Column "loan_status" descript Loan approval status: 1 = approved; 0 = rejected
2. Loan will be rejected if "previous_loan_defaults_on_file" is yes

Task:
1. List all data quality (target leakage or lable leakage if presented) or modelling-readiness issues.
2. Suggest action to remedy the issues.

Important:
- Do not assume external knowledge.
- Do not say to drop a column just because it is listed as a warning.
- Keep the answer concise. Do not write modelling code yet.
"""


if client is not None:
    response = client.responses.create(
        model=OPENAI_MODEL,
        input=quality_prompt
    )
    print('\nLLM response:')
    print(response.output_text)
else:
    print('\nNo API response because client is not connected. Copy the prompt above into your chatbot.')

# This cell asks the LLM to review the dataset profile for modelling-readiness issues.
# The LLM does not receive the full dataset, only the summary stored in payload_text.
# The prompt asks for possible issues and practical remedies.
# The instructions help prevent the LLM from making unsupported assumptions or dropping columns too quickly.
# If the API client is connected, the prompt is sent automatically.
# Otherwise, students can copy the prompt and use the chatbot manually.

LLM response:
## 1) Data quality / modelling-readiness issues (incl. potential leakage)

1. **Target leakage / label leakage risk via stated relationship**
   - You noted: *“Loan will be rejected if `previous_loan_defaults_on_file` is yes”*.
   - If this rule holds strongly in the training data (near-deterministic), tree models can essentially learn the label from that feature. This is not “label leakage” (the feature isn’t the target), but it **creates an overly-easy / potentially unstable model** that may fail under distribution shift.

2. **Possible label-equivalent information**
   - `loan_status` is the target, and it’s sometimes common in such datasets that certain features are recorded *after* the decision process.
   - In your data, **`previous_loan_defaults_on_file` could plausibly be derived/confirmed as part of the same underwriting decision pipeline** that determines approval. You can’t prove that from the profile alone, but the near-deterministic pattern you observed is a readiness concern.

3. **Severe outliers in key numeric inputs**
   - `person_age` max is **144** (IQR outliers: 4.86%).
   - `person_income` max is **7,200,766** (IQR outliers: 4.93%).
   - `person_emp_exp` max is **125** (outlier: 3.83%).
   - `loan_amnt` max is **35,000** but still has outlier rate 5.22%.
   - These may indicate data entry errors, unit inconsistencies, or heavy-tailed distributions. Tree models can handle outliers, but **they can overfit to corrupted/extreme values**.

4. **Feature scaling/robustness not addressed (tree models still can be affected)**
   - While decision trees don’t require scaling, the presence of extreme values means splits may be driven by outliers, hurting generalization.

5. **Class imbalance**
   - `loan_status` has `mean = 0.22`, meaning ~22% approved / 78% rejected.
   - If unaddressed, many models will optimize accuracy poorly for the minority class.

6. **High-cardinality / many unique numeric-like features (interaction complexity)**
   - `person_income` has **33,989 unique** values; `loan_int_rate` has **1,302 unique**; `loan_amnt` has **4,483 unique**.
   - Not “bad” per se, but readiness-wise it increases the chance that trees grow very specific thresholds unless regularized.

7. **Potential data quality issues indicated by distributions**
   - `cb_person_cred_hist_length` has only 29 unique values and outlier rate 3.04%; `credit_score` outlier rate 1.04%.
   - This suggests discretized/limited reporting for some credit fields, which can create step-like decision behavior that may not transfer well if reporting differs.

8. **Train/test split risk with strong rule**
   - With the “previous defaults ⇒ rejection” behavior, if the split is random you’re likely to get similar underwriting cohorts; if split is by time/customer cohort (unknown), the rule may break.
   - Readiness issue: **you need to validate performance under an appropriate splitting strategy**.

---

## 2) Suggested actions to remedy issues

1. **Verify/quantify the suspected leakage-like behavior**
   - Compute the approval rate conditioned on `previous_loan_defaults_on_file` and measure how close to deterministic it is (e.g., difference in approval rate, and performance degradation when this feature is excluded).
   - If performance collapses without it, treat the model as **“credit-history-driven”** and assess stability with robust validation (see below).

2. **Check “when” each field is known**
   - Confirm whether `previous_loan_defaults_on_file` is available *before* the decision is made (in your dataset’s construction).
   - If it is obtained/validated during underwriting after the decision, that’s true leakage in many production setups; if not, it’s just a very predictive feature—still fine, but document it.

3. **Handle outliers with data validation and robust preprocessing**
   - Run sanity checks:
     - age should be in a realistic range (e.g., verify whether 144 is a true value or encoding error),
     - income/emp_exp should be plausible given the domain definitions you have.
   - If they look erroneous, correct them; if they look valid but extreme, consider robust transformations (e.g., winsorization/capping or log1p transforms) or regularization strategies during model training.

4. **Address class imbalance**
   - Use imbalance-aware training/evaluation (e.g., class weights or sampling) and report metrics beyond accuracy (ROC-AUC / PR-AUC, recall for approved class, etc.).

5. **Use careful validation strategy**
   - Ensure the validation split matches how the model will be used:
     - If there’s any notion of time/period, use time-based splits.
     - If “customers” repeat across rows (not indicated), split by customer to avoid memorization (no ID column detected, but confirm uniqueness assumptions).

6. **Limit overfitting of highly specific thresholds**
   - Use tree regularization controls (max depth, min samples per leaf, min samples split, etc.) and compare performance across folds to ensure the “defaults ⇒ rejection” rule isn’t causing brittle overfit.

7. **Document feature/target relationship**
   - Even if not formal leakage, document that `previous_loan_defaults_on_file` is a strong driver of `loan_status` and include it in model interpretability outputs (feature importance / partial dependence) to support risk review.

If you want, I can outline a quick checklist of specific statistics to compute next (e.g., conditional approval rates, KS/quantile checks for outliers, and validation split recommendations) without writing any code.

In [9]:
quality_prompt2 = f"""
Generate code to fix each of the following issues, only for data cleaning purposes, do not model yet.
Input is df, and output should be cleaned_df.
Issues:
{response.output_text}
"""


if client is not None:
    response2 = client.responses.create(
        model=OPENAI_MODEL,
        input=quality_prompt2
    )
    print('\nLLM response:')
    print(response2.output_text)
else:
    print('\nNo API response because client is not connected. Copy the prompt above into your chatbot.')

# This cell asks the LLM to generate Python code for data cleaning.
# It uses the earlier LLM response, response.output_text, as the list of issues to fix.
# The instruction says not to build a model yet, only prepare a cleaned version of the data.
# The expected input is df, and the expected output is cleaned_df.
# If the API client is connected, the code suggestion is generated automatically.
# Otherwise, students can copy the prompt and use the chatbot manually.

LLM response:
```python
import numpy as np
import pandas as pd

# Assumes input dataframe is named `df`
cleaned_df = df.copy()

# -----------------------------
# Helper functions
# -----------------------------
def to_numeric_safe(s):
    """Convert to numeric when possible; otherwise return original."""
    try:
        return pd.to_numeric(s, errors="ignore")
    except Exception:
        return s

def standardize_yes_no(x):
    """Map common variants to 'yes'/'no' (keeps NaN)."""
    if pd.isna(x):
        return np.nan
    v = str(x).strip().lower()
    if v in {"yes", "y", "1", "true", "t"}:
        return "yes"
    if v in {"no", "n", "0", "false", "f"}:
        return "no"
    return x  # leave unknown tokens as-is

def cap_iqr_outliers(series, k=1.5):
    """Winsorize using IQR caps (data cleaning / robustness)."""
    x = series.astype(float)
    q1 = x.quantile(0.25)
    q3 = x.quantile(0.75)
    iqr = q3 - q1
    if pd.isna(iqr) or iqr == 0:
        return x
    lo = q1 - k * iqr
    hi = q3 + k * iqr
    return x.clip(lo, hi)

# -----------------------------
# 1) Basic type cleanup
# -----------------------------
# Convert obvious numeric columns to numeric (data cleaning)
numeric_cols = [
    "person_age", "person_income", "person_emp_exp", "loan_amnt",
    "loan_int_rate", "loan_percent_income", "cb_person_cred_hist_length",
    "credit_score"
]
for c in numeric_cols:
    if c in cleaned_df.columns:
        cleaned_df[c] = pd.to_numeric(cleaned_df[c], errors="coerce")

# Standardize yes/no fields if present
yn_cols = ["previous_loan_defaults_on_file"]
for c in yn_cols:
    if c in cleaned_df.columns:
        cleaned_df[c] = cleaned_df[c].map(standardize_yes_no)

# Ensure target is consistent (do not change semantics)
# If loan_status exists and seems like yes/no or mixed, normalize to {0,1}
if "loan_status" in cleaned_df.columns:
    # Common case: 0/1 already
    if cleaned_df["loan_status"].dtype == object:
        v = cleaned_df["loan_status"].astype(str).str.strip().str.lower()
        mapping = {
            "1": 1, "true": 1, "approved": 1, "yes": 1,
            "0": 0, "false": 0, "rejected": 0, "no": 0
        }
        cleaned_df["loan_status"] = v.map(mapping).where(v.notna(), np.nan)
    cleaned_df["loan_status"] = pd.to_numeric(cleaned_df["loan_status"], errors="coerce")

# Drop rows with no target label (cleaning)
if "loan_status" in cleaned_df.columns:
    cleaned_df = cleaned_df[cleaned_df["loan_status"].notna()].copy()

# -----------------------------
# 2) Sanity checks & outlier handling (data cleaning only)
# -----------------------------
# Hard plausibility ranges (domain-inspired; adjust if you know true business constraints)
# Purpose: fix likely entry/unit errors before any modeling.
range_specs = {
    "person_age": (18, 100),               # 144 likely an error
    "person_income": (0, 1e7),            # keep non-negative; cap extreme
    "person_emp_exp": (0, 60),            # 125 likely an error
    "loan_amnt": (0, 1e6),
    "loan_int_rate": (0, 100),            # percent
    "loan_percent_income": (0, 100),     # percent
    "cb_person_cred_hist_length": (0, 1000),
    "credit_score": (0, 2000)           # depending on bureau system
}

for col, (lo, hi) in range_specs.items():
    if col in cleaned_df.columns:
        # Mark implausible values as NaN (rather than silently clipping),
        # then impute later (or drop if you prefer).
        s = cleaned_df[col]
        cleaned_df.loc[(s < lo) | (s > hi), col] = np.nan

# Winsorize remaining numeric outliers to reduce extreme influence
# (addresses severe outliers; keeps general distribution shape)
winsor_cols = ["person_age", "person_income", "person_emp_exp", "loan_amnt"]
for col in winsor_cols:
    if col in cleaned_df.columns:
        # Only apply winsorization if there are enough non-null values
        if cleaned_df[col].notna().sum() > 10:
            cleaned_df[col] = cap_iqr_outliers(cleaned_df[col], k=1.5)

# -----------------------------
# 3) Handle missing values (cleaning)
# -----------------------------
# Simple imputations; you can refine later.
# Keep categorical as mode, numeric as median.
for c in cleaned_df.columns:
    if c in numeric_cols and c in cleaned_df.columns:
        if cleaned_df[c].isna().any():
            cleaned_df[c] = cleaned_df[c].fillna(cleaned_df[c].median())
    elif c in ["loan_status"]:
        continue
    else:
        # For categorical/object columns (small set), fill with mode
        if cleaned_df[c].dtype == object and cleaned_df[c].isna().any():
            mode = cleaned_df[c].mode(dropna=True)
            if len(mode) > 0:
                cleaned_df[c] = cleaned_df[c].fillna(mode.iloc[0])

# -----------------------------
# 4) Encoding readiness for yes/no-like fields
# -----------------------------
# Convert previous_loan_defaults_on_file to binary numeric for readiness.
if "previous_loan_defaults_on_file" in cleaned_df.columns:
    cleaned_df["previous_loan_defaults_on_file"] = (
        cleaned_df["previous_loan_defaults_on_file"].map({"yes": 1, "no": 0})
    )
    # If any unknown tokens remain, set to NaN then impute
    if cleaned_df["previous_loan_defaults_on_file"].isna().any():
        cleaned_df["previous_loan_defaults_on_file"] = cleaned_df["previous_loan_defaults_on_file"].fillna(
            cleaned_df["previous_loan_defaults_on_file"].median()
        )

# -----------------------------
# 5) Duplicate handling
# -----------------------------
cleaned_df = cleaned_df.drop_duplicates().reset_index(drop=True)

# -----------------------------
# 6) Prepare label-leakage risk handling (cleaning only)
# -----------------------------
# Do NOT remove the feature yet automatically (that would be a modeling/validation decision),
# but we can "flag" potential near-determinism by creating a QA column.
# This is still cleaning/QA, not dropping.
if "previous_loan_defaults_on_file" in cleaned_df.columns and "loan_status" in cleaned_df.columns:
    # Compute conditional approval rates (global) for QA
    # (Use only for diagnostics; doesn't change features.)
    # If you prefer not to compute anything, remove this block.
    prev = cleaned_df["previous_loan_defaults_on_file"]
    y = cleaned_df["loan_status"]
    # Avoid divide-by-zero
    appr_given_prev1 = y[prev == 1].mean() if (prev == 1).any() else np.nan
    appr_given_prev0 = y[prev == 0].mean() if (prev == 0).any() else np.nan
    cleaned_df.attrs["qa_conditional_approval_prev1"] = appr_given_prev1
    cleaned_df.attrs["qa_conditional_approval_prev0"] = appr_given_prev0

# -----------------------------
# Final checks
# -----------------------------
# Ensure no inf values remain
cleaned_df = cleaned_df.replace([np.inf, -np.inf], np.nan)
# Re-impute any residual NaNs after inf cleanup
for c in cleaned_df.columns:
    if cleaned_df[c].isna().any():
        if pd.api.types.is_numeric_dtype(cleaned_df[c]):
            cleaned_df[c] = cleaned_df[c].fillna(cleaned_df[c].median())
        else:
            mode = cleaned_df[c].mode(dropna=True)
            cleaned_df[c] = cleaned_df[c].fillna(mode.iloc[0] if len(mode) else "")

# cleaned_df is the cleaned dataset
```

In [23]:
# Assumes input dataframe is named `df`
cleaned_df = df.copy()

# -----------------------------
# Helper functions
# -----------------------------
def to_numeric_safe(s):
    """Convert to numeric when possible; otherwise return original."""
    try:
        return pd.to_numeric(s, errors="ignore")
    except Exception:
        return s

def standardize_yes_no(x):
    """Map common variants to 'yes'/'no' (keeps NaN)."""
    if pd.isna(x):
        return np.nan
    v = str(x).strip().lower()
    if v in {"yes", "y", "1", "true", "t"}:
        return "yes"
    if v in {"no", "n", "0", "false", "f"}:
        return "no"
    return x  # leave unknown tokens as-is

def cap_iqr_outliers(series, k=1.5):
    """Winsorize using IQR caps (data cleaning / robustness)."""
    x = series.astype(float)
    q1 = x.quantile(0.25)
    q3 = x.quantile(0.75)
    iqr = q3 - q1
    if pd.isna(iqr) or iqr == 0:
        return x
    lo = q1 - k * iqr
    hi = q3 + k * iqr
    return x.clip(lo, hi)

# -----------------------------
# 1) Basic type cleanup
# -----------------------------
# Convert obvious numeric columns to numeric (data cleaning)
numeric_cols = [
    "person_age", "person_income", "person_emp_exp", "loan_amnt",
    "loan_int_rate", "loan_percent_income", "cb_person_cred_hist_length",
    "credit_score"
]
for c in numeric_cols:
    if c in cleaned_df.columns:
        cleaned_df[c] = pd.to_numeric(cleaned_df[c], errors="coerce")

# Standardize yes/no fields if present
yn_cols = ["previous_loan_defaults_on_file"]
for c in yn_cols:
    if c in cleaned_df.columns:
        cleaned_df[c] = cleaned_df[c].map(standardize_yes_no)

# Ensure target is consistent (do not change semantics)
# If loan_status exists and seems like yes/no or mixed, normalize to {0,1}
if "loan_status" in cleaned_df.columns:
    # Common case: 0/1 already
    if cleaned_df["loan_status"].dtype == object:
        v = cleaned_df["loan_status"].astype(str).str.strip().str.lower()
        mapping = {
            "1": 1, "true": 1, "approved": 1, "yes": 1,
            "0": 0, "false": 0, "rejected": 0, "no": 0
        }
        cleaned_df["loan_status"] = v.map(mapping).where(v.notna(), np.nan)
    cleaned_df["loan_status"] = pd.to_numeric(cleaned_df["loan_status"], errors="coerce")

# Drop rows with no target label (cleaning)
if "loan_status" in cleaned_df.columns:
    cleaned_df = cleaned_df[cleaned_df["loan_status"].notna()].copy()

# -----------------------------
# 2) Sanity checks & outlier handling (data cleaning only)
# -----------------------------
# Hard plausibility ranges (domain-inspired; adjust if you know true business constraints)
# Purpose: fix likely entry/unit errors before any modeling.
range_specs = {
    "person_age": (18, 100),               # 144 likely an error
    "person_income": (0, 1e7),            # keep non-negative; cap extreme
    "person_emp_exp": (0, 80),            # 125 likely an error
    "loan_amnt": (0, 1e6),
    "loan_int_rate": (0, 100),            # percent
    "loan_percent_income": (0, 100),     # percent
    "cb_person_cred_hist_length": (0, 1000),
    "credit_score": (0, 2000)           # depending on bureau system
}

for col, (lo, hi) in range_specs.items():
    if col in cleaned_df.columns:
        # Mark implausible values as NaN (rather than silently clipping),
        # then impute later (or drop if you prefer).
        s = cleaned_df[col]
        cleaned_df.loc[(s < lo) | (s > hi), col] = np.nan

# Winsorize remaining numeric outliers to reduce extreme influence
# (addresses severe outliers; keeps general distribution shape)
winsor_cols = ["person_age", "person_income", "person_emp_exp", "loan_amnt"]
for col in winsor_cols:
    if col in cleaned_df.columns:
        # Only apply winsorization if there are enough non-null values
        if cleaned_df[col].notna().sum() > 10:
            cleaned_df[col] = cap_iqr_outliers(cleaned_df[col], k=1.5)

# -----------------------------
# 3) Handle missing values (cleaning)
# -----------------------------
# Simple imputations; you can refine later.
# Keep categorical as mode, numeric as median.
for c in cleaned_df.columns:
    if c in numeric_cols and c in cleaned_df.columns:
        if cleaned_df[c].isna().any():
            cleaned_df[c] = cleaned_df[c].fillna(cleaned_df[c].median())
    elif c in ["loan_status"]:
        continue
    else:
        # For categorical/object columns (small set), fill with mode
        if cleaned_df[c].dtype == object and cleaned_df[c].isna().any():
            mode = cleaned_df[c].mode(dropna=True)
            if len(mode) > 0:
                cleaned_df[c] = cleaned_df[c].fillna(mode.iloc[0])

# -----------------------------
# 4) Encoding readiness for yes/no-like fields
# -----------------------------
# Convert previous_loan_defaults_on_file to binary numeric for readiness.
if "previous_loan_defaults_on_file" in cleaned_df.columns:
    cleaned_df["previous_loan_defaults_on_file"] = (
        cleaned_df["previous_loan_defaults_on_file"].map({"yes": 1, "no": 0})
    )
    # If any unknown tokens remain, set to NaN then impute
    if cleaned_df["previous_loan_defaults_on_file"].isna().any():
        cleaned_df["previous_loan_defaults_on_file"] = cleaned_df["previous_loan_defaults_on_file"].fillna(
            cleaned_df["previous_loan_defaults_on_file"].median()
        )

# -----------------------------
# 5) Duplicate handling
# -----------------------------
cleaned_df = cleaned_df.drop_duplicates().reset_index(drop=True)

# -----------------------------
# 6) Prepare label-leakage risk handling (cleaning only)
# -----------------------------
# Do NOT remove the feature yet automatically (that would be a modeling/validation decision),
# but we can "flag" potential near-determinism by creating a QA column.
# This is still cleaning/QA, not dropping.
if "previous_loan_defaults_on_file" in cleaned_df.columns and "loan_status" in cleaned_df.columns:
    # Compute conditional approval rates (global) for QA
    # (Use only for diagnostics; doesn't change features.)
    # If you prefer not to compute anything, remove this block.
    prev = cleaned_df["previous_loan_defaults_on_file"]
    y = cleaned_df["loan_status"]
    # Avoid divide-by-zero
    appr_given_prev1 = y[prev == 1].mean() if (prev == 1).any() else np.nan
    appr_given_prev0 = y[prev == 0].mean() if (prev == 0).any() else np.nan
    cleaned_df.attrs["qa_conditional_approval_prev1"] = appr_given_prev1
    cleaned_df.attrs["qa_conditional_approval_prev0"] = appr_given_prev0

# -----------------------------
# Final checks
# -----------------------------
# Ensure no inf values remain
cleaned_df = cleaned_df.replace([np.inf, -np.inf], np.nan)
# Re-impute any residual NaNs after inf cleanup
for c in cleaned_df.columns:
    if cleaned_df[c].isna().any():
        if pd.api.types.is_numeric_dtype(cleaned_df[c]):
            cleaned_df[c] = cleaned_df[c].fillna(cleaned_df[c].median())
        else:
            mode = cleaned_df[c].mode(dropna=True)
            cleaned_df[c] = cleaned_df[c].fillna(mode.iloc[0] if len(mode) else "")

# cleaned_df is the cleaned dataset

In [21]:
# ============================================================
# DATA CLEANING ONLY
# ============================================================

cleaned_df = df.copy()

# ------------------------------------------------------------
# 1. Convert expected numeric columns
# ------------------------------------------------------------
numeric_cols = [
    "person_age",
    "person_income",
    "person_emp_exp",
    "loan_amnt",
    "loan_int_rate",
    "loan_percent_income",
    "cb_person_cred_hist_length",
    "credit_score"
]

for col in numeric_cols:
    if col in cleaned_df.columns:
        cleaned_df[col] = pd.to_numeric(
            cleaned_df[col], errors="coerce"
        )

# ------------------------------------------------------------
# 2. Standardise categorical text
# ------------------------------------------------------------
categorical_cols = [
    "person_gender",
    "person_education",
    "person_home_ownership",
    "loan_intent",
    "previous_loan_defaults_on_file"
]

for col in categorical_cols:
    if col in cleaned_df.columns:
        cleaned_df[col] = (
            cleaned_df[col]
            .astype("string")
            .str.strip()
        )

# Standardise Yes/No field
if "previous_loan_defaults_on_file" in cleaned_df.columns:
    cleaned_df["previous_loan_defaults_on_file"] = (
        cleaned_df["previous_loan_defaults_on_file"]
        .str.lower()
        .replace({
            "y": "yes",
            "1": "yes",
            "true": "yes",
            "n": "no",
            "0": "no",
            "false": "no"
        })
    )

# ------------------------------------------------------------
# 3. Validate target
# ------------------------------------------------------------
if "loan_status" in cleaned_df.columns:

    # Convert target to numeric
    cleaned_df["loan_status"] = pd.to_numeric(
        cleaned_df["loan_status"],
        errors="coerce"
    )

    # Keep only valid target labels: 0 = rejected, 1 = approved
    invalid_target = ~cleaned_df["loan_status"].isin([0, 1])

    print("Invalid target records:", invalid_target.sum())

    cleaned_df.loc[invalid_target, "loan_status"] = np.nan

    # Target is required, so remove records without a valid label
    cleaned_df = cleaned_df[
        cleaned_df["loan_status"].notna()
    ].copy()

# ------------------------------------------------------------
# 4. Replace infinite values
# ------------------------------------------------------------
cleaned_df = cleaned_df.replace(
    [np.inf, -np.inf],
    np.nan
)

# ------------------------------------------------------------
# 5. Business-rule validation
# ------------------------------------------------------------

# Age: 18–100
invalid_age = ~cleaned_df["person_age"].between(18, 100)
print("Invalid age records:", invalid_age.sum())
cleaned_df.loc[invalid_age, "person_age"] = np.nan

# Employment experience: 0–80 years
invalid_exp = ~cleaned_df["person_emp_exp"].between(0, 80)
print("Invalid employment experience:", invalid_exp.sum())
cleaned_df.loc[invalid_exp, "person_emp_exp"] = np.nan

# Income must be positive
invalid_income = cleaned_df["person_income"] <= 0
print("Invalid income records:", invalid_income.sum())
cleaned_df.loc[invalid_income, "person_income"] = np.nan

# Loan amount must be positive
invalid_loan = cleaned_df["loan_amnt"] <= 0
print("Invalid loan amount records:", invalid_loan.sum())
cleaned_df.loc[invalid_loan, "loan_amnt"] = np.nan

# Interest rate: 0–100%
invalid_rate = ~cleaned_df["loan_int_rate"].between(0, 100)
print("Invalid interest rate records:", invalid_rate.sum())
cleaned_df.loc[invalid_rate, "loan_int_rate"] = np.nan

# Loan percentage income is stored as a ratio: 0–1
invalid_percent_income = ~cleaned_df[
    "loan_percent_income"
].between(0, 1)

print(
    "Invalid loan-percent-income records:",
    invalid_percent_income.sum()
)

cleaned_df.loc[
    invalid_percent_income,
    "loan_percent_income"
] = np.nan

# Credit history cannot be negative
invalid_credit_history = (
    cleaned_df["cb_person_cred_hist_length"] < 0
)

print(
    "Invalid credit-history records:",
    invalid_credit_history.sum()
)

cleaned_df.loc[
    invalid_credit_history,
    "cb_person_cred_hist_length"
] = np.nan

# Credit score: use observed/business-valid range
invalid_credit_score = ~cleaned_df[
    "credit_score"
].between(300, 850)

print(
    "Invalid credit-score records:",
    invalid_credit_score.sum()
)

cleaned_df.loc[
    invalid_credit_score,
    "credit_score"
] = np.nan

# ------------------------------------------------------------
# 6. Logical consistency checks
# ------------------------------------------------------------

# Employment experience should not exceed plausible working years
invalid_age_exp = (
    cleaned_df["person_emp_exp"].notna()
    & cleaned_df["person_age"].notna()
    & (
        cleaned_df["person_emp_exp"]
        > cleaned_df["person_age"] - 18
    )
)

print(
    "Age/employment inconsistency:",
    invalid_age_exp.sum()
)

cleaned_df.loc[
    invalid_age_exp,
    "person_emp_exp"
] = np.nan

# Credit history should not exceed plausible years since age 18
invalid_age_credit = (
    cleaned_df["cb_person_cred_hist_length"].notna()
    & cleaned_df["person_age"].notna()
    & (
        cleaned_df["cb_person_cred_hist_length"]
        > cleaned_df["person_age"] - 18
    )
)

print(
    "Age/credit-history inconsistency:",
    invalid_age_credit.sum()
)

cleaned_df.loc[
    invalid_age_credit,
    "cb_person_cred_hist_length"
] = np.nan

# ------------------------------------------------------------
# 7. Check categorical values
# ------------------------------------------------------------

expected_categories = {
    "person_gender": {"male", "female"},
    "person_education": {
        "Bachelor", "Associate", "High School",
        "Master", "Doctorate"
    },
    "person_home_ownership": {
        "RENT", "MORTGAGE", "OWN", "OTHER"
    },
    "loan_intent": {
        "EDUCATION", "MEDICAL", "VENTURE",
        "PERSONAL", "DEBTCONSOLIDATION",
        "HOMEIMPROVEMENT"
    },
    "previous_loan_defaults_on_file": {
        "yes", "no"
    }
}

for col, expected in expected_categories.items():
    if col in cleaned_df.columns:
        unexpected = ~cleaned_df[col].isin(expected)

        print(
            f"{col} - unexpected values:",
            unexpected.sum()
        )

        cleaned_df.loc[unexpected, col] = np.nan

# ------------------------------------------------------------
# 8. Remove duplicate records
# ------------------------------------------------------------

duplicates = cleaned_df.duplicated().sum()

print("Duplicate records:", duplicates)

cleaned_df = (
    cleaned_df
    .drop_duplicates()
    .reset_index(drop=True)
)

# ------------------------------------------------------------
# 9. Final cleaning checks
# ------------------------------------------------------------

print("\n=== FINAL CLEANING CHECK ===")
print("Shape:", cleaned_df.shape)
print("Duplicates:", cleaned_df.duplicated().sum())

print("\nMissing values:")
print(
    cleaned_df.isna()
    .sum()
    .sort_values(ascending=False)
)

print("\nTarget distribution:")
print(
    cleaned_df["loan_status"]
    .value_counts(dropna=False)
)

# cleaned_df = cleaned dataset

Invalid target records: 0
Invalid age records: 7
Invalid employment experience: 7
Invalid income records: 0
Invalid loan amount records: 0
Invalid interest rate records: 0
Invalid loan-percent-income records: 0
Invalid credit-history records: 0
Invalid credit-score records: 0
Age/employment inconsistency: 0
Age/credit-history inconsistency: 873
person_gender - unexpected values: 0
person_education - unexpected values: 0
person_home_ownership - unexpected values: 0
loan_intent - unexpected values: 0
previous_loan_defaults_on_file - unexpected values: 0
Duplicate records: 0

=== FINAL CLEANING CHECK ===
Shape: (45000, 14)
Duplicates: 0

Missing values:
cb_person_cred_hist_length        873
person_age                          7
person_emp_exp                      7
person_gender                       0
person_income                       0
person_education                    0
person_home_ownership               0
loan_amnt                           0
loan_int_rate                       0
loan_intent                         0
loan_percent_income                 0
credit_score                        0
previous_loan_defaults_on_file      0
loan_status                         0
dtype: int64

Target distribution:
loan_status
0.0    35000
1.0    10000
Name: count, dtype: int64

In [24]:
print('Original rows:', df.shape[0])
print('Cleaned rows:', cleaned_df.shape[0])

print('\nMissing values after cleaning:')
missing_after_cleaning = cleaned_df.isna().sum()
display(missing_after_cleaning.sort_values(ascending=False).head(10))

print('\nColumns after cleaning:')
print(cleaned_df.columns.tolist())

Original rows: 45000
Cleaned rows: 45000

Missing values after cleaning:

person_age               0
person_gender            0
person_education         0
person_income            0
person_emp_exp           0
person_home_ownership    0
loan_amnt                0
loan_intent              0
loan_int_rate            0
loan_percent_income      0
dtype: int64

Columns after cleaning:
['person_age', 'person_gender', 'person_education', 'person_income', 'person_emp_exp', 'person_home_ownership', 'loan_amnt', 'loan_intent', 'loan_int_rate', 'loan_percent_income', 'cb_person_cred_hist_length', 'credit_score', 'previous_loan_defaults_on_file', 'loan_status']

In [25]:
cleaned_df.head(85)

,person_age,person_gender,person_education,person_income,person_emp_exp,person_home_ownership,loan_amnt,loan_intent,loan_int_rate,loan_percent_income,cb_person_cred_hist_length,credit_score,previous_loan_defaults_on_file,loan_status
0,22.0,female,Master,71948.000,0.0,RENT,23093.125,PERSONAL,16.02,0.49,3.0,561.0,0,1
1,21.0,female,High School,12282.000,0.0,OWN,1000.000,EDUCATION,11.14,0.08,2.0,504.0,1,0
2,25.0,female,High School,12438.000,3.0,MORTGAGE,5500.000,MEDICAL,12.87,0.44,3.0,635.0,0,1
3,23.0,female,Bachelor,79753.000,0.0,RENT,23093.125,MEDICAL,15.23,0.44,2.0,675.0,0,1
4,24.0,male,Master,66135.000,1.0,RENT,23093.125,MEDICAL,14.27,0.53,4.0,586.0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
80,24.0,male,Bachelor,168667.125,2.0,RENT,18000.000,EDUCATION,12.98,0.06,3.0,671.0,0,0
81,26.0,male,Bachelor,168667.125,4.0,RENT,4800.000,VENTURE,13.57,0.02,3.0,789.0,0,0
82,25.0,female,Bachelor,121062.000,1.0,RENT,23093.125,DEBTCONSOLIDATION,12.69,0.23,3.0,622.0,0,0
83,26.0,male,Associate,133372.000,1.0,RENT,23093.125,EDUCATION,8.90,0.21,2.0,538.0,1,0
84,26.0,male,Bachelor,15505.000,0.0,OWN,2700.000,DEBTCONSOLIDATION,11.01,0.17,4.0,587.0,0,1